---

- hosts: all_servers
  become: true
  tasks:
  
    - name: Stop pgpool
      service:
       name: pgpool2
       state: stopped

    - name: Stop postgresql
      service:
       name: postgresql
       state: stopped

    - name: Start postgresql
      service:
       name: postgresql
       state: started

    - name: Start pgpool2
      service:
       name: pgpool2
       state: started
