---

- hosts: all_servers
  become: true
  become_user: root
  tasks:

  - name: Remove "pgpool2" package
    apt:
     name: pgpool2
     state: absent
     autoremove: true
     purge: true	
    
  - name: Set up pgpool repo
    shell: |
     echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    args:
     warn: no

  - name: Install pgpool
    apt:
     name: 
      - pgpool2
      - libpgpool2 
      - postgresql-13-pgpool2
     update_cache: yes

  #- name: Stop postgresql
    #service:
      #name: postgresql
      #state: stopped

 # - name: Stop pgpool2
   # service:
     # name: pgpool2
      #state: stopped


